### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by timbeissinger** [kate-crosby/sfsGBS#1]
Yo Kate! Can you do this without removing non-polymorphic SNPs? I think doing so is just a matter of changing this part: 

for file in *.gz
do
        echo "$file: " $(~/bin/vcftools_0.1.12b/bin/vcftools --gzvcf $file --min-alleles 2 --max-alleles 2 --recode --out biallelic_$file)
done

**Comment by kate-crosby** [comment]
Yup. On it. Will close when done.
